import tkinter as tk
from decryptor import Decryptor

main = Decryptor("ifmmpuifsfnzobnfjtjssfmfwboujbngspnuiftpvuitjefpgbwfszgbnpvtdjuzboeibwfdpnfupfotmbwfbmmuibuzpvbsfxfmmbdrvbjoufeupjbmtpmjlfupfbuuiftfwfszqpqvmbsdifftfcvshfstcfdbvtfuifzbmmpxgpsnfupxbmlbcpvuuiftdippmbsfbboefokpznzefmjdjpvtmvodixjuipvucfjohjoufssvqufenjetfoufodfxijdijtwfszjodsfejcmzojdf")

while True:
    main.cli()